name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ecfd146a4eba3c212c6de7b3c265a5a9189aeb757f83dd7aa08051b997b494"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
