name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef58d9bffef137f5b640673c8ba45ffdbac70045b90e315b097e611c41e1ef48"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
