name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4289969ec27bfa7d30dd05ba331f3758a0e0e7fc70e45c0f7f78f4252f8203e0"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
