name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d6a6788fbbfe9dd53b19944d439c5a6b27a5a5145628230702e2b39efd45cab"

[versions]
forge = "40.1.23"
minecraft = "1.18.2"
