name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad515f31346425f8c4adc92779d771564e934811cc8517d81e58aac6fe32f42"

[versions]
forge = "40.1.23"
minecraft = "1.18.2"
