name = "Shooty McShoot Face"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79aa3c1dcd79ea5137742a9fbed3f4bc937cbb0fbea65ba62f9e6d863713246d"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"

[options]
acceptable-game-versions = "1.18.1"
