name = "Shooty McShootFace"
author = "OldWorldOrder"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07326f4fb0992555cf9f2dff61ade0548414fc72fb34447fba71c6a0bcc76c9b"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
